#!/bin/sh -e

cd $(dirname $0)
job="$1" ; [ "$job" ] || job="test"

function downloadBinary() {
	wget -q -O "deps/bin/$1" "https://raw.github.com/amatiasq/Bin/master/$1"
	chmod +x "deps/bin/$1"
}

case $job in


	test)
		dart test/life.test.dart
		;;


	js-test)
		frogc test/life.test.dart
		;;


	run)
		dart lub/main.dart
		;;


	js)
		frogc lib/main.dart
		;;


	copyright)
		deps/bin/copyright dart
		;;


	deps)
		mkdir deps/bin
		downloadBinary copyright
		git submodule update
		;;


esac
